services:
  foundry:
    image: felddy/foundryvtt:12
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_LICENSE_KEY=${FOUNDRY_LICENSE_KEY}
      - FOUNDRY_HOSTNAME=localhost
      - FOUNDRY_LOCAL_HOSTNAME=localhost
      - FOUNDRY_PROTOCOL=4
      - FOUNDRY_PROXY_PORT=30000
      - FOUNDRY_PROXY_SSL=false
      - FOUNDRY_WORLD=test-world
    ports:
      - "30000:30000"
    volumes:
      # Use a named volume for data persistence
      - foundry-test-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - foundry-test

networks:
  foundry-test:
    driver: bridge

volumes:
  foundry-test-data:
