folder: zLDylBwEWWuq3B0v
name: Environmental Adaptation
type: spell
_id: GflqEGGkgWMVeKyX
img: icons/magic/air/wind-weather-sailing-ship.webp
system:
  activities:
    6N6FSP6ZtZFpiltD:
      type: utility
      _id: 6N6FSP6ZtZFpiltD
      sort: 0
      activation:
        type: action
        value: null
        override: false
        condition: ''
      consumption:
        scaling:
          allowed: false
        spellSlot: false
        targets:
          - type: itemUses
            value: '2'
            target: Compendium.sosly-5e-house-rules.classes.Item.yXFJ10Lf7yDyu5OM
            scaling:
              mode: ''
      description:
        chatFlavor: ''
      duration:
        units: hour
        value: '1'
        concentration: false
        override: false
      effects: []
      range:
        units: touch
        override: false
        special: ''
      target:
        template:
          contiguous: false
          units: ft
          type: ''
        affects:
          choice: false
          type: creature
          count: '1'
          special: ''
        override: false
        prompt: true
      uses:
        spent: 0
        recovery: []
        max: ''
      roll:
        prompt: false
        visible: false
        name: ''
        formula: ''
      name: 2 Psi Points
      img: ''
      appliedEffects: []
  uses:
    spent: 0
    recovery: []
    max: ''
  description:
    value: >-
      <p>As an action, you or a creature you touch ignores the effects of
      extreme heat or cold (but not cold or fire damage) for the next hour.</p>
      <p><!-- TODO: Review implementation - ignoring extreme heat/cold
      environmental effects must be tracked manually --></p>
    chat: ''
  identifier: environmental-adaptation
  source:
    revision: 1
    rules: '2024'
  activation:
    type: action
    value: null
    condition: ''
  duration:
    units: hour
    value: '1'
  level: 99
  materials:
    value: ''
    consumed: false
    cost: 0
    supply: 0
  preparation:
    mode: psionic
    prepared: false
  properties: []
  range:
    units: touch
    special: ''
  school: imm
  target:
    template:
      contiguous: false
      units: ft
      type: ''
    affects:
      choice: false
      type: creature
      count: '1'
      special: ''
effects: []
sort: 0
ownership:
  default: 0
  NbCXvDXaYhqPCRFb: 3
flags:
  dnd5e:
    riders:
      activity: []
      effect: []
_stats:
  compendiumSource: null
  duplicateSource: null
  coreVersion: '12.331'
  systemId: dnd5e
  systemVersion: 4.4.4
  createdTime: null
  modifiedTime: null
  lastModifiedBy: null
_key: '!items!GflqEGGkgWMVeKyX'
