import {logger} from './utils/logger';
import {registerBreatherFeature} from './features/breather/index';
import {registerNetworthFeature} from './features/networth/index';
import {registerMadnessFeature} from './features/madness/index';
import {registerImperiledFeature} from './features/imperiled/index';
import {registerConcentrationFeature} from './features/concentration/index';
import {registerMultipleConcentrationFeature} from './features/multiple-concentration/index';
import {registerRestEnhancementsFeature} from './features/rest-enhancements/index';
import {registerToolsFeature} from './features/tools/index';
import {registerItemIdentificationFeature} from './features/item-identification/index';
import {registerEncumbranceFeature} from './features/encumbrance/index';
import {registerTransformationCleanupFeature} from './features/transformation-cleanup/index';
import {registerLocationFeature} from './features/location/index';
import {registerPsionicsFeature} from './features/psionics/index.js';
import {registerSeveredLandsBloodMagicFeature} from './features/severed-lands-blood-magic/index';
import {registerBeastFormFeature} from './features/beast-form/index';
import {registerLowLightVisionFeature} from './features/low-light-vision/index';
import {registerInfravisionFeature} from './features/infravision/index';
import {registerLanguageChoiceFeature} from './features/language-choice/index';
import {registerVision5eCompatibility} from './features/vision-5e-compatibility/index';
import {registerLevelsRegionVisibilityFeature} from './features/levels-region-visibility/index';

Hooks.once('init', async () => {
    registerEncumbranceFeature();
    registerBreatherFeature();
    registerNetworthFeature();
    registerMadnessFeature();
    registerImperiledFeature();
    registerConcentrationFeature();
    registerMultipleConcentrationFeature();
    registerRestEnhancementsFeature();
    registerToolsFeature();
    registerItemIdentificationFeature();
    registerLanguageChoiceFeature();
    registerTransformationCleanupFeature();
    registerLocationFeature();
    registerPsionicsFeature();
    registerSeveredLandsBloodMagicFeature();
    registerBeastFormFeature();
    registerLowLightVisionFeature();
    registerInfravisionFeature();
    registerVision5eCompatibility();
    registerLevelsRegionVisibilityFeature();
    logger.info('Initialized');
});
