name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build module
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.test.yml"
        env:
          FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
          FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
          FOUNDRY_LICENSE_KEY: ${{ secrets.FOUNDRY_LICENSE_KEY }}

      - name: Wait for FoundryVTT to start
        run: |
          # Wait for Foundry to be healthy
          echo "Waiting for FoundryVTT to start..."
          for i in {1..60}; do
            if curl -f http://localhost:30000; then
              echo "FoundryVTT is ready!"
              break
            fi
            echo "Waiting... ($i/60)"
            sleep 5
          done
          
          # Give it a few more seconds to fully initialize
          sleep 10

      - name: Install sosly module
        run: |
          echo "Installing sosly module..."
          docker compose -f docker-compose.test.yml cp ./ foundry:/data/Data/modules/sosly-5e-house-rules/

      - name: Configure Foundry
        run: node tools/setup_foundry.mjs

      - name: Run integration tests
        run: npm run test:integration

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failures
          path: test-results/
          retention-days: 7

      - name: Docker logs
        if: failure()
        run: docker compose -f docker-compose.test.yml logs

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.test.yml down
